name: avdan
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.7.3+15

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  url_launcher: ^6.0.9
  just_audio: ^0.9.5
  sensors_plus: ^1.0.2
  in_app_purchase: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.0
  flutter_lints: ^1.0.4

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash_light.png
  color_dark: "#121212"
  image_dark: assets/splash_dark.png
  web_image_mode: contain

flutter:
  uses-material-design: true
  assets:
    - assets/localization.json
    - assets/languages.json
    - assets/chapters.json
    - assets/flags/

    - assets/images/animals/
    - assets/images/body parts/
    - assets/images/city/
    - assets/images/clothes/
    - assets/images/food/
    - assets/images/fruits/
    - assets/images/home/
    - assets/images/nature/
    - assets/images/numbers/
    - assets/images/people/
    - assets/images/pronouns/
    - assets/images/vegetables/
    - assets/images/verbs/

    - assets/audio/iron/alphabet/
    - assets/audio/iron/animals/
    - assets/audio/iron/body parts/
    - assets/audio/iron/city/
    - assets/audio/iron/clothes/
    - assets/audio/iron/food/
    - assets/audio/iron/fruits/
    - assets/audio/iron/home/
    - assets/audio/iron/nature/
    - assets/audio/iron/numbers/
    - assets/audio/iron/people/
    - assets/audio/iron/pronouns/
    - assets/audio/iron/vegetables/
    - assets/audio/iron/verbs/

    - assets/audio/digor/alphabet/
    - assets/audio/digor/animals/
    - assets/audio/digor/body parts/
    - assets/audio/digor/city/
    - assets/audio/digor/clothes/
    - assets/audio/digor/food/
    - assets/audio/digor/fruits/
    - assets/audio/digor/home/
    - assets/audio/digor/nature/
    - assets/audio/digor/numbers/
    - assets/audio/digor/people/
    - assets/audio/digor/pronouns/
    - assets/audio/digor/vegetables/
    - assets/audio/digor/verbs/
