name: avdan
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.7+64

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.20.0
  cloud_firestore: ^4.12.0
  firebase_storage: ^11.4.0
  url_launcher: ^6.2.0
  provider: ^6.0.5
  google_fonts: ^6.1.0
  package_info_plus: ^4.2.0
  infinite_scroll_pagination: ^4.0.0
  intersperse: ^2.0.0
  flutter_markdown: ^0.6.18
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.18.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  archive: ^3.4.6
  soundpool: ^2.4.1
  firebase_analytics: ^10.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter_launcher_icons:
  image_path: "assets/icon.png"
  android: "launcher_icon"
  adaptive_icon_background: "#000000"
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
