name: avdan
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.9.8+28

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.19.2
  cloud_firestore: ^3.3.0
  firebase_storage: ^10.3.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.4
  just_audio: ^0.9.27
  sensors_plus: ^1.3.2
  provider: ^6.0.3
  google_fonts: ^3.0.1
  package_info_plus: ^1.4.2
  infinite_scroll_pagination: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/

    - assets/images/animals/
    - assets/images/body parts/
    - assets/images/city/
    - assets/images/belongings/
    - assets/images/food/
    - assets/images/fruits/
    - assets/images/home/
    - assets/images/nature/
    - assets/images/numbers/
    - assets/images/people/
    - assets/images/pronouns/
    - assets/images/vegetables/
    - assets/images/verbs/
    - assets/images/ornament/
    # - assets/images/adjectives/
    # - assets/images/colors/

    - assets/audio/digor/alphabet/
    - assets/audio/digor/animals/
    - assets/audio/digor/body parts/
    - assets/audio/digor/city/
    - assets/audio/digor/belongings/
    - assets/audio/digor/food/
    - assets/audio/digor/fruits/
    - assets/audio/digor/home/
    - assets/audio/digor/nature/
    - assets/audio/digor/numbers/
    - assets/audio/digor/people/
    - assets/audio/digor/pronouns/
    - assets/audio/digor/vegetables/
    - assets/audio/digor/verbs/
    # - assets/audio/digor/adjectives/
    # - assets/audio/digor/colors/

    - assets/audio/iron/alphabet/
    - assets/audio/iron/animals/
    - assets/audio/iron/body parts/
    - assets/audio/iron/city/
    - assets/audio/iron/belongings/
    - assets/audio/iron/food/
    - assets/audio/iron/fruits/
    - assets/audio/iron/home/
    - assets/audio/iron/nature/
    - assets/audio/iron/numbers/
    - assets/audio/iron/people/
    - assets/audio/iron/pronouns/
    - assets/audio/iron/vegetables/
    - assets/audio/iron/verbs/
    # - assets/audio/iron/adjectives/
    # - assets/audio/iron/colors/

    - assets/audio/kaitag/alphabet/
    - assets/audio/kaitag/animals/
    - assets/audio/kaitag/body parts/
    - assets/audio/kaitag/city/
    - assets/audio/kaitag/belongings/
    - assets/audio/kaitag/food/
    - assets/audio/kaitag/fruits/
    - assets/audio/kaitag/home/
    - assets/audio/kaitag/nature/
    - assets/audio/kaitag/numbers/
    - assets/audio/kaitag/people/
    - assets/audio/kaitag/pronouns/
    - assets/audio/kaitag/vegetables/
    - assets/audio/kaitag/verbs/
    - assets/audio/kaitag/adjectives/
    - assets/audio/kaitag/colors/

    - assets/audio/abkhaz/alphabet/
    - assets/audio/abkhaz/animals/
    - assets/audio/abkhaz/body parts/
    - assets/audio/abkhaz/city/
    - assets/audio/abkhaz/belongings/
    - assets/audio/abkhaz/food/
    - assets/audio/abkhaz/fruits/
    - assets/audio/abkhaz/home/
    - assets/audio/abkhaz/nature/
    - assets/audio/abkhaz/numbers/
    - assets/audio/abkhaz/people/
    - assets/audio/abkhaz/pronouns/
    - assets/audio/abkhaz/vegetables/
    - assets/audio/abkhaz/verbs/
    - assets/audio/abkhaz/adjectives/
    - assets/audio/abkhaz/colors/

    - assets/audio/dargwa/alphabet/
    - assets/audio/dargwa/animals/
    - assets/audio/dargwa/body parts/
    - assets/audio/dargwa/city/
    - assets/audio/dargwa/belongings/
    - assets/audio/dargwa/food/
    - assets/audio/dargwa/fruits/
    - assets/audio/dargwa/home/
    - assets/audio/dargwa/nature/
    - assets/audio/dargwa/numbers/
    - assets/audio/dargwa/people/
    - assets/audio/dargwa/pronouns/
    - assets/audio/dargwa/vegetables/
    - assets/audio/dargwa/verbs/
    - assets/audio/dargwa/adjectives/
    - assets/audio/dargwa/colors/

    # - assets/audio/east circassian/alphabet/
    # - assets/audio/east circassian/animals/
    # - assets/audio/east circassian/body parts/
    # - assets/audio/east circassian/city/
    # - assets/audio/east circassian/belongings/
    # - assets/audio/east circassian/food/
    # - assets/audio/east circassian/fruits/
    # - assets/audio/east circassian/home/
    # - assets/audio/east circassian/nature/
    # - assets/audio/east circassian/numbers/
    # - assets/audio/east circassian/people/
    # - assets/audio/east circassian/pronouns/
    # - assets/audio/east circassian/vegetables/
    # - assets/audio/east circassian/verbs/
    # - assets/audio/east circassian/adjectives/
    # - assets/audio/east circassian/colors/

    - assets/audio/kubachi/alphabet/
    - assets/audio/kubachi/people/
    - assets/audio/kubachi/food/
    - assets/audio/kubachi/home/
    - assets/audio/kubachi/animals/
    - assets/audio/kubachi/numbers/
    - assets/audio/kubachi/ornament/
