name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: |
          flutter pub get
          flutter pub run build_runner build
          flutter build web
          echo "avdan.raxys.app" > build/web/CNAME

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
